//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab5v18
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public string ISBN { get; set; }
        public string Authors { get; set; }
        public int PublisherId { get; set; }
        public Nullable<int> PublicationYear { get; set; }
    
        public virtual Publishers Publishers { get; set; }
    }
}
